// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import UploadWidgetController from "./upload_widget_controller"
application.register("upload-widget", UploadWidgetController)

import VideoUploadFormController from "./video_upload_form_controller"
application.register("video-upload-form", VideoUploadFormController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import HlsPlayerController from "./hls_player_controller"
application.register("hls-player", HlsPlayerController)